# Generated by Django 2.2.6 on 2019-11-01 10:22

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Youtube',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(blank=True, max_length=250, null=True)),
                ('video_url', models.URLField(blank=True, null=True)),
                ('duration', models.IntegerField(blank=True, null=True)),
                ('views', models.IntegerField(blank=True, null=True)),
                ('thumbnail_image', models.ImageField(blank=True, null=True, upload_to='thumbnail/photos/')),
                ('original_full_sized', models.ImageField(blank=True, null=True, upload_to='original/photos')),
            ],
        ),
    ]
